backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "posts"
    label: "Postagens"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    path: "{{slug}}/index"  # <-- importante!
    preview_path: "blog/{{slug}}"  # <-- para preview no CMS
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Imagem de capa", name: "thumbnail", widget: "image" }
      - { label: "Corpo", name: "body", widget: "markdown" }
