backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "posts"
    label: "Postagens"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    frontmatter:
      layout: "post.njk"
      permalink: "/post/{{slug}}/index.html"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - label: "Imagem de capa"
        name: "thumbnail"
        widget: "image"
        media_library:
          config:
            public_path: /img/uploads/
      - { label: "Corpo", name: "body", widget: "markdown" }
