backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "posts"
    label: "Postagens"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Imagem de capa", name: "thumbnail", widget: "image" }
      - { label: "Corpo", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "post.njk" }
      - { label: "Permalink", name: "permalink", widget: "hidden", default: "blog/{{slug}}/index.html" }
